name: Security Scan

on:
  push:
    branches: [ main ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Lecture de la configuration dynamique
      - name: Set image to scan
        run: |
          echo "IMAGE_TO_SCAN=$(cat demo-config)" >> $GITHUB_ENV

      # 0. Installation de jq
      - name: Install jq
        run: sudo apt-get install jq -y

      # 1. Scan Trivy - S'ARRÊTE SI FAILLE CRITIQUE/HIGH
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_TO_SCAN }}
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
        # continue-on-error a été supprimé pour bloquer le pipeline

      # 2. Filtrage du rapport Trivy (S'exécute seulement si le scan a réussi)
      - name: Filter Trivy report
        run: |
          jq '{SchemaVersion: .SchemaVersion, ArtifactName: .ArtifactName, Results: [.Results[]? | {Target: .Target, Class: .Class, Vulnerabilities: [.Vulnerabilities[]? | select(.Severity == "CRITICAL" or .Severity == "HIGH")]}]}' trivy-report.json > trivy-report-light.json

      # 3. Import Trivy vers DefectDojo (S'exécute toujours pour avoir le rapport même en cas d'échec)
      - name: Import Trivy to DefectDojo
        if: always()
        env:
          DD_API_TOKEN: ${{ secrets.DD_API_TOKEN }}
          DD_URL: ${{ secrets.DD_URL }}
        run: |
          curl -v -X POST "${DD_URL}/api/v2/import-scan/" \
               -H "Authorization: Token ${DD_API_TOKEN}" \
               -H "Bypass-Tunnel-Reminder: true" \
               -F "scan_type=Trivy Scan" \
               -F "file=@trivy-report-light.json" \
               -F "product_name=DevSecOps-Pipeline" \
               -F "engagement_name=CI-CD-Pipeline" \
               -F "auto_create_context=true"

      # 4. Import Kyverno
      - name: Import Kyverno to DefectDojo
        if: always()
        env:
          DD_API_TOKEN: ${{ secrets.DD_API_TOKEN }}
          DD_URL: ${{ secrets.DD_URL }}
        run: |
          curl -v -X POST "${DD_URL}/api/v2/import-scan/" \
               -H "Authorization: Token ${DD_API_TOKEN}" \
               -F "scan_type=Generic Findings Import" \
               -F "file=@kyverno_dojo.json" \
               -F "product_name=DevSecOps-Pipeline" \
               -F "engagement_name=CI-CD-Pipeline" \
               -F "auto_create_context=true"
