name: Security Scan

on:
  push:
    branches: [ main ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Lecture de la configuration dynamique
      - name: Set image to scan
        run: |
          echo "IMAGE_TO_SCAN=$(cat demo-config)" >> $GITHUB_ENV

      # 0. Installation de jq
      - name: Install jq
        run: sudo apt-get install jq -y

      # 1. Scan Trivy - S'ARRÊTE SI FAILLE CRITIQUE/HIGH
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_TO_SCAN }}
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # 2. Filtrage du rapport Trivy (S'exécute seulement si le scan Trivy n'a pas échoué)
      - name: Filter Trivy report
        if: always()
        run: |
          if [ -f trivy-report.json ]; then
            jq '{SchemaVersion: .SchemaVersion, ArtifactName: .ArtifactName, Results: [.Results[]? | {Target: .Target, Class: .Class, Vulnerabilities: [.Vulnerabilities[]? | select(.Severity == "CRITICAL" or .Severity == "HIGH")]}]}' trivy-report.json > trivy-report-light.json
          else
            echo "{}" > trivy-report-light.json
          fi

      # 3. Import Trivy vers DefectDojo (S'exécute toujours)
      - name: Import Trivy to DefectDojo
        if: always()
        env:
          DD_API_TOKEN: ${{ secrets.DD_API_TOKEN }}
          DD_URL: ${{ secrets.DD_URL }}
        run: |
          if [ -s trivy-report-light.json ]; then
            curl -v -X POST "${DD_URL}/api/v2/import-scan/" \
                 -H "Authorization: Token ${DD_API_TOKEN}" \
                 -H "Bypass-Tunnel-Reminder: true" \
                 -F "scan_type=Trivy Scan" \
                 -F "file=@trivy-report-light.json" \
                 -F "product_name=DevSecOps-Pipeline" \
                 -F "engagement_name=CI-CD-Pipeline" \
                 -F "auto_create_context=true"
          else
            echo "Rapport Trivy vide ou inexistant, saut de l'import."
          fi

      # 4. Import Kyverno
      - name: Import Kyverno to DefectDojo
        if: always()
        env:
          DD_API_TOKEN: ${{ secrets.DD_API_TOKEN }}
          DD_URL: ${{ secrets.DD_URL }}
        run: |
          if [ -f kyverno_dojo.json ]; then
            curl -v -X POST "${DD_URL}/api/v2/import-scan/" \
                 -H "Authorization: Token ${DD_API_TOKEN}" \
                 -F "scan_type=Generic Findings Import" \
                 -F "file=@kyverno_dojo.json" \
                 -F "product_name=DevSecOps-Pipeline" \
                 -F "engagement_name=CI-CD-Pipeline" \
                 -F "auto_create_context=true"
          else
            echo "Fichier kyverno_dojo.json non trouvé, saut de l'import."
          fi
